module.exports = {

    authCookieSize: parseInt(process.env.AUTH_COOKIE_SIZE),
    authCookieName: 'auth',
    authDurationSeconds: parseInt(process.env.AUTH_SECONDS),
    authProviderName: 'auth_provider',
    authRegisterUrl: process.env.AUTH_REGISTER_URL,
    doubleSubmitCookieBytesLength: parseInt(process.env.DOUBLE_SUBMIT_COOKIE_SIZE),
    doubleSubmitCookieName: 'double_submit',
    doubleSubmitHeaderName: 'x-double-submit',
    enableCustomAuth: process.env.ENABLE_CUSTOM_AUTH === 'true',
    emailHost: process.env.EMAIL_SMTP,
    emailPort: parseInt(process.env.EMAIL_PORT),
    emailSecure: process.env.EMAIL_SECURE === 'true',
    emailUser: process.env.EMAIL_USER,
    emailPassword: process.env.EMAIL_PASSWORD,
    emailFromName: process.env.EMAIL_FROM_NAME,
    emailFromEmail: process.env.EMAIL_FROM_EMAIL,
    jsonPrefix: process.env.PREFIX,
    minAgeForRegistration: parseInt(process.env.REGISTER_MIN_AGE),
    passwordMinLength: process.env.PASSWORD_MIN_LENGTH === 'true',
    redirectCookieName: 'login_redirect',
    registrationAuthSize: parseInt(process.env.REGISTER_AUTH_SIZE),
    registrationConfirmationCookieSize: parseInt(process.env.REGISTER_CONFIRMATION_SIZE),
    registrationConfirmationTimeoutSeconds: parseInt(process.env.REGISTER_TIMEOUT_SECONDS),
    registrationConfirmationUrl: process.env.REGISTER_CONFIRMATION_URL,
    registrationConfirmationRedirectUrl: process.env.REGISTER_CONFIRMATION_REDIRECT_URL,
    registrationConfirmationTitle: process.env.REGISTER_CONFIRMATION_TITLE,
    passwordChangeNotificationTitle: process.env.PASSWORD_CHANGE_NOTIFICATION_TITLE,
    resetPasswordConfirmationTitle: process.env.RESET_PASSWORD_CONFIRMATION_TITLE,
    resetPasswordConfirmationUrl: process.env.RESET_PASSWORD_CONFIRMATION_URL,
    resetPasswordConfirmationTimeoutSeconds: parseInt(process.env.RESET_PASSWORD_TIMEOUT_SECONDS),
    resetPasswordNewPasswordSize: parseInt(process.env.RESET_PASSWORD_NEW_PASSWORD_SIZE),
    statusCodes: {
        ok: 0,
        invalidParameters: 1,
        throttled: 11
    },
    trustForwardedIP: process.env.TRUST_FORWARDED_IP === 'true',
    throttleRegisterCustomAuthSeconds: parseInt(process.env.REGISTER_CUSTOM_AUTH_THROTTLING),
    throttleLoginCustomAuthSeconds: parseInt(process.env.LOGIN_CUSTOM_AUTH_THROTTLING),
    throttleChangePasswordCustomAuthSeconds: parseInt(process.env.CHANGE_PASSWORD_CUSTOM_AUTH_THROTTLING),
    throttleResetPasswordCustomAuthSeconds: parseInt(process.env.RESET_PASSWORD_CUSTOM_AUTH_THROTTLING),
    useSecureCookies: process.env.SECURE_COOKIES === 'true'
};
